### ISSUE TITLE
Positioning Statement

### ISSUE THREAD

**Issue by Cade5480** [IanTDuncan/MealTime#15]
The problem of (what) affects (who), the impact of which is ... . A successful solution would be ... .

**Comment by bdshanks-28** [comment]
The problem of being overweight affects all kinds of people, the impact of which is an unhealthy life and possible sickness and health complications. A successful solution would be weight loss which is difficult for many and sometimes what is healthy and what isn't is hard to track which is why we are designing our app to try and help combat those issue sone would encounter when trying to diet.

Think about this?

**Comment by Cade5480** [comment]
So the problem in this day and age is everyone thinks they can do a little physical activity, but continue to eat what they want and loose weight. Not being able to loose the weight you are expecting to can easily lead to self-doubt, depression, and anxiety. These same people might not know 90% of loosing weights starts with the nutrients that you are intaking. Our solution to this issue is to create a free way to be able to track the amount of macros you are absorbing on a day to day basis to successfully loose weight.

**Comment by aaleksandraristic** [comment]
@bdshanks-28 I like your comment, we can definitely go with it! I would only add some more details of our app or specific features (we can adjust the story according to what we offer). What do you think? 

@Cade5480 I like how you mentioned self-doubt, depression, and anxiety because we can really increase self-satisfaction and encourage people that they are doing something good and healthy for their health. We can also mention that this process of tracking macros and nutrients is going to be simplified so it's not gonna be difficult to use.

**Comment by Cade5480** [comment]
This looks good! I’m sure we can close soon!

**Comment by IanTDuncan** [comment]
The problem of managing what you eat while keeping an optimal caloric intake affects many people, the impact of which leads to obesity and further health risks such as heart disease. Managing your meals and exercising regularly go a long way in living a healthy lifestyle, but it is meals that truly determine healthiness. As such, our solution is our app, MealTime, which will track and plan meals as well as record calories and other nutrition information.

Wanted to put in my own piece before it closed, let me know if this is just a regurgitation of the earlier comments.

**Comment by BeepDroid** [comment]
The problem today is attaining a healthy lifestyle while surrounded by high caloric food that's often easier to obtain, especially in the hustle and bustle of today's day-to-day. This impacts people of all ages, classes, and positions in life, and causes problems with energy levels, overall health, and can severely impact self-worth. MealTime brings a solution by providing an easily accesible way to manage your meals and intake.

I too wanted to make one, but I really like the previous one's mentioned!

**Comment by Cade5480** [comment]
I would say we could look to close this issue, what do y'all think?

**Comment by bdshanks-28** [comment]
Agreed!

**Comment by Cade5480** [comment]
Sounds good we can go with mine if that one sounds ok, we will get everyone's opinion on this.

**Comment by bdshanks-28** [comment]
Yours is definitely is better.
