### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#39]
What is App Localization? And How Does it Compare to Internationalization?

Link from the Moodle: https://clevertap.com/blog/what-is-app-localization/#:~:text=App%20localization%20is%20the%20process,country%20as%20it%20is%20within

**Comment by BeepDroid** [comment]
App localization is: "the process of changing and refining an app in order to appeal to a geographically specific target market. You want to make sure that your app is as appealing and easy to use outside your headquarters’ country as it is within." (From https://clevertap.com/blog/what-is-app-localization/#:~:text=App%20localization%20is%20the%20process,country%20as%20it%20is%20within )

From reading the tips provided on the website, one way we can achieve localization is making sure the date and time our app reads is always accurate according to timezones and formatting. Given our app is so food based, we would also have to ensure we're not only providing foods we're used to, and include dishes from different cultures/locations, where those ingredients will be more readily accessible. 

The difference between app internationalization and app localization is that internationalization is focused majorly on the developmental process -- like actually coding in the switching process between time zones. Localization is collecting the data for the different time zones -- again, as an example -- and is more focused on the content consumed by end-users. 

Here is an excerpt from "Summa Lingea" that I think sums it up well: 
"Internationalization: coding the assistants in such a way that they can easily switch between languages.
Localization: collecting data in different languages and dialects to train their speech recognition engines."
(Link for use as it also describes globalization: https://summalinguae.com/localization/globalization-vs-internationalization-vs-localization/#:~:text=Internationalization%3A%20coding%20the%20assistants%20in,train%20their%20speech%20recognition%20engines )

**Comment by aaleksandraristic** [comment]
Good comparison with internationalization. Looks great!

**Comment by Cade5480** [comment]
That was an easy read with some good comparisons and explanations! Good job Kerrigan!!

**Comment by IanTDuncan** [comment]
Since our app will have a variety of different foods/meals from across the world, do think we should have our app contain multiple languages? If so would it be even feasible to implement multiple languages?

**Comment by aaleksandraristic** [comment]
Yeah, that's a good question. It would be nice to implement multiple languages since we will have international food as well. 
I guess we can start with just one language and then see how difficult it is to implement the rest of them.

**Comment by BeepDroid** [comment]
I think expanding to just one or two different languages at first would be good for us starting out, focusing on the most common ones in our initial area. According to search results, that would be Spanish and Chinese (Primarily Mandarin and Cantonese dialects I think)

**Comment by IanTDuncan** [comment]
I think Spanish would be the easiest to implement, Chinese maybe a tad too difficult
