### ISSUE TITLE
Monitoring the app

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#40]
https://www.bugsnag.com/
	   App is crashing...
	   Disability - to determine what is crashing

**Comment by IanTDuncan** [comment]
### Monitoring the App 
A bug report contains device logs, stack traces, and other diagnostic information to help you find and fix bugs in your app. Since our app is being developed in Android studio, a java based IDE, we have plenty of options to choose from when monitoring our app which will be mentioned below for both in-house and customer bug reports.

**Bug Testing**
- Capture bug reports from any physical testing
- Capture a bug report from the Android Emulator
- Capture a bug report using Android Debug Bridge (adb)
- Save older bug reports 
- Inspect the bug report zip file

**User Reports**
- Google Play Console
- Firebase crash reporting

**Comment by aaleksandraristic** [comment]
Are we going to choose one option out of all of these or we can implement more than one? 
Are there any big differences between them?

**Comment by IanTDuncan** [comment]
I don't see any big problems with implementing multiple, the only problem that I could see if we use multiple is that runtime performance may be impacted. 
The only difference for Bug Testing is whether we're using an actual Android device or the Android simulator, but I presume most, if not all of us, will be using the Android simulator. 
For User Reports, I'd have to examine each of them individually, but Firebase also functions as a data tracking tool while Google Play Console does not.

**Comment by Cade5480** [comment]
The listed bug testing and user reports looks good, like Ian said, I think we could implement multiple if we need to.

**Comment by IanTDuncan** [comment]
I'll go ahead and close the issue for now, can reopen if we need too
