### ISSUE TITLE
CI Pipeline

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#48]
Here is the PDF for the Pipeline:
[Agile development.pdf](https://github.com/IanTDuncan/MealTime/files/13112456/Agile.development.pdf)

Divided into the following issues: 

- **Build Stage with Android Studio**

- **Unit and Continuous Testing**

- **Quality Checking with Static Code Analyzers**

- **Store Build Files, including APK, for Deployment**

**Comment by IanTDuncan** [comment]
### CI Integration Via GitHub

I figured I would research continuous integration using GitHub first since that seems to be what we'll be primarily using to store and update our code.

- On the top menu bar of GitHub, you'll be able to find a tab called Actions 
- This allows us to generate workflows which can be used for **deployment, security, continuous integration, automation,** and **pages**

As mentioned above using the Actions tab on GitHub we'll be able to generate a workflow for continuous integration. Since, I already uploaded some test code, we've gotten suggestions to implement an Android CI for our code, but I would like to discuss that with the team before committing to that. Finally, I believe the Actions tab will be relevant to Issue #49 -  CD Pipeline and recommend looking into it.

**Comment by Cade5480** [comment]
The whole idea is wanting to catch issues early in our development process, I have made a list of things that have to due with the CI Pipeline to maybe be aware of as we continue into the month of November.

**Choosing the CI Service** - This is simply choosing a service that integrates well with GitHub and so we will be using GitHub Actions like Ian mentioned prior.

**Create a Configuration File** - CI services use a configuration file (e.g., .github/workflows/main.yml for GitHub Actions) to define your pipeline. This file outlines the steps your CI pipeline will follow, like linting, testing, and deployment.

**Testing Stage** - Put our pipeline through a testing stage, which is running our unit tests and other tests if we use them to validate our code behaves as we expect it to.

**Deployment Stage** - If all tests pass, we can deploy our application to the public for testing.

**Triggers** - Specify when we our pipeline should run. Typically it will trigger on every push to specific branches or pull requests.

**Comment by IanTDuncan** [comment]
### CI Integration Via Firebase
While GitHub will be mainly used for our project, I feel limiting our options to only GitHub so early in research is not a good idea. As such I have researched additional continuous integration for android studio itself and have found out Firebase also provides CI services.

**Integration Via Firebase Only Requires 3 things**

1. Google Cloud
2. A service account
3. Enabling required APIs

Additionally, Firebase allows integration with GitHub as mentioned below:

> If you use GitHub or another revision control system to manage the source code for your app, you can configure Jenkins to run automated builds and run tests each time updates to your app are checked in. You can also configure Jenkins to run builds periodically.

I will do more research into this option to make sure it's suitable, but in the meantime [here](https://firebase.google.com/docs/test-lab/android/continuous) is the article where this is all pulled from.

**Comment by aaleksandraristic** [comment]
Good job guys! Everything that you have found make sense. I have created sub-issues for all the stages and assigned them to you. Do you think we need something else to add as an issue or these 4 are good?
