### ISSUE TITLE
Use UI Automator or Jetpack Compose

### ISSUE THREAD

**Issue by aaleksandraristic** [IanTDuncan/MealTime#56]

**Comment by BeepDroid** [comment]
[Here's something that might be useful for jetpack, a script for the automation testing itself](https://stackoverflow.com/questions/71564618/automation-testing-framework-for-jetpack-compose)

**Comment by BeepDroid** [comment]
[Accessing composable with UI Automator](https://medium.com/androiddevelopers/accessing-composables-from-uiautomator-cf316515edc2)

**Comment by BeepDroid** [comment]
Okay, so, some more details on UIAutomator. From what I've found, UIAutomator allows us to build the UI (no surprise there) and write in automated tests using Selenium, Appium or Espresso. These test scripts can be written in Java, Javascript, or Python, and can ".. interact with the real device and will run automatically, as if a user is interacting." ([Source](https://www.waldo.com/blog/android-ui-automator#:~:text=The%20UIAutomator%20or%20UIAutomator%20APIs,Java%2C%20JavaScript%2C%20or%20Python.) )

UIAutomator also has a list of [APIs](https://developer.android.com/training/testing/other-components/ui-automator#ui-automator) that we would be able to use to write more "robust" and complex tests. This particular list is linked to Espresso as the script, and Espresso uses Java and JUnit. So far, in UIAutomator, we're looking at a heavier Java language load. 

Meanwhile, for Jetpack Compose uses the Kotlin programming language, which "s fully declarative, meaning you describe your UI by calling a series of functions that transform data into a UI hierarchy."  ( [Source](https://developer.android.com/codelabs/jetpack-compose-basics#0) ) far as I can gather, Jetpack does not require Espresso, Selenium, or Appium. However, you are able to USE Espresso with Jetpack Compose. Compose seems to have a seepter learning curve. The scripts I've followed along with and written weren't hard to understand, but it is definitely a new language.

**Comment by BeepDroid** [comment]
So, we've verbally agreed to use Jetpack Compose over UI Automator. Because of that, there's really no need for me to go into extreme detail about Appium or Selenium, as they won't be used with Jetpack. Now, the APIs I previously listed were with Espresso through Jetpack. It is not necessary for us to implement Espresso, but it is an option. Jetpack Compose is already a framework with built-in classes such as "ComposeTestRule" for Unit Testing and the "AndroidJUnitRunner" for Integration Testing (which "allows developers to test the integration of different code units, ensuring that they work together correctly and that any changes made to one unit don't break the functionality of another.") Now the Android JUnit Runner does require the Android X Test Library. [ [Source](https://www.waldo.com/blog/getting-started-with-testing-with-compose)  

Espresso uses JUnit. so I don't think we'll be using it with Jetpack in order to avoid any language entanglements; however, research says it provides even more libraries and tools for UI Testing, but again, as it is not a required framework, I personally don't feel we should implement it unless deemed necessary/more useful than troublesome.

Thoughts on this?
